# Polyglitch: Line Width on dashboard knobs didn't work - always bounces back to 63.
# had to change it to Num Lines.
from vjmagic import constants
config = {
'name': 'hypnodrome_alpha',
'clips': [
[36, 'Moon', [], False] ,
[37, 'Longry', [], False] ,
[38, 'Ocean Series', [], False] ,
[39, 'Infected Series', [], False] ,
[44, 'Max Cooper - Waves', [], False] ,
[45, 'MAX COOPER SEED', [], False] ,
[46, 'corollaria generation', [], False] ,
[47, 'For Approval', [], False] ,
[52, 'Playgrounds Titles', [], False] ,
[53, 'SHHH! - Jack Sachs X Tate Britain', [], False] ,
[54, 'Patterns', [], False] ,
[55, 'brainslushy', [], False] ,
[60, 'LORN - ANVIL', [], False] ,
[61, 'Kerli - Blossom [mv]', [], False] ,
[62, 'S~U~R', [], False] ,
[63, 'just diffuse', [], False] ,
[40, "Reggie Watts - If You're Fcking, You're Fcking", [], False] ,
[41, 'Kerli - Feral Hearts [mv]', [], False] ,
[42, 'Jose Gonzalez Bouncy Balls', [], False] ,
[43, 'Powers of Ten', [], False] ,
[48, 'Major Lazer - Lean On [mv]', [], False] ,
[49, 'Major Lazer - Light it Up [mv]', [], False] ,
[50, ' V E R S U S', [], False] ,
[51, 'Welcome To Our World', [], False] ,
[56, 'Heavy Blanket', [], False] ,
[57, 'Click Bait [as]', [], False] ,
[58, 'Beautiful Cacti Bloom Before Your Eyes', [], False] ,
[59, 'Black Ocean _ Ecosystem & Incubation', [], False] ,
[64, 'KLJM ESOL', [], False] ,
[65, 'Voxel Bumps', [], False] ,
[66, 'Crazy speed', [], False] ,
[67, 'A BEAUTIFUL PERSON', [], False] ,
[69, 'Cyberscope ', ['Angles', 'Rotate', 'Cyber', 'C-Pass', ''], False] ,
[70, 'Fux Given', ['Rings', 'Parts', 'Fux', 'Lag', 'Twirl'], False] ,
[71, 'Lawl of Mirrors', ['Ocean', 'Flipper', 'Mirror', 'Mirror', 'Mirror', 'Mirror', ''], False] ,
[77, 'Blow&Blur', ['BlowX', 'BlowY', 'Blur', 'Splits', 'Screens'], False] ,
[78, 'Point Grid ', ['Points', 'Reso', 'Worms', 'Trails', 'Quads', '', '', ''], False] ,
[79, 'Polyglitch', ['Color', 'Lines', 'Expand', 'Zoom', 'Fuzz'], False] ,
[85, 'Pixelnoise', ['Noise', 'Reso', 'Satch', 'Fountain'], False] ,
[86, 'Spleigher ', ['Fun', 'Slay', 'Contra', 'Distort', 'Brite', ''], False] ,
[87, 'Salvia', ['Bonkers', 'Tmelines', 'Copies', 'Folds', '', ''], False] ,
[93, 'Rotating Panels', ['Craze', 'Edge', 'Confuse'], False] ,
[94, 'Happy Trails', ['Trails', 'Perma'], False] ,
[95, 'Tritunnel ', ['Tunnel', 'Speed', 'TurnX', 'TurnY', 'Fractality', '', ''], False] ,
[72, 'Audiosucker ', ['Suck', 'Poster'], True] ,
[73, 'Busta Rhymes ', ['Invert', 'Focus', ''], True] ,
[74, 'Stripwreck ', ['Yank', 'Tug', 'Strip', 'Wreck'], True] ,
[80, 'Bzzzt ', ['RGB', 'Zoom', 'Light', 'Frames'], True] ,
[81, 'Intersectional ', ['Thin', 'Rate'], True] ,
[82, 'Wiggity Wack ', ['Wiggity', 'Floor It', 'Cellular', 'Deckade'], True] ,
[88, 'Posterize ', ['Posters', 'Satch'], True] ,
[89, 'Oil Fire ', ['Distort', 'Spd', 'Deeds'], True] ,
[90, 'Chance of Hail ', ['SlowPour', 'Size', 'Twist', 'Blue ^', 'Red v'], True] ,
[96, 'Dubs ', ['Dubs', 'Drops'], True] ,
[97, 'Triangulate ', ['Fractlty', 'Gentle'], True] ,
[98, 'Ballmer ', ['Shape', '3D Reso', '2D Reso', 'Darkweb'], True] ,
],
'quadrants': [{
  'mode': 'BASIC',
  'active': 6,
  'quadrant': 2,
  'palette': 1,
  'killer': constants.BUTTON_DELETE,
  'kill_other_layer_on_select': 1,
  'labels': ['STR', 'MAG', 'INT', 'DEX', 'CON', 'LCK'],
  'keys': [
    69, 70, 71,
    77, 78, 79,
    85, 86, 87,
    93, 94, 95
  ],
}, {
  'mode': 'BASIC',
  'active': 6,
  'quadrant': 3,
  'palette': 2,
  'killer': constants.BUTTON_UNDO,
  'kill_other_layer_on_select': 0,
  'keys': [
    72, 73, 74,
    80, 81, 82,
    88, 89, 90,
    96, 97, 98
  ],
}, {
  'mode': 'CLIPS',
  'active': 6,
  'quadrant': 0,
  'palette': 0,
  'killer': constants.BUTTON_QUANTIZE,
  'kill_other_layer_on_select': 3,
  'labels': [''],
  'keys': [
    36, 37, 38, 39,
    44, 45, 46, 47,
    52, 53, 54, 55,
    60, 61, 62, 63
  ]
}, {
  'mode': 'CLIPS',
  'active': 6,
  'quadrant': 1,
  'palette': 0,
  'killer': constants.BUTTON_DOUBLE,
  'kill_other_layer_on_select': 2,
  'labels': ['intro', 'verse', 'chorus', 'bridge', 'break', 'outro'],
  'keys': [
    40, 41, 42, 43,
    48, 49, 50, 51,
    56, 57, 58, 59,
    64, 65, 66, 67
    ]
  }]
}
