from vjmagic import constants
config = {
'name': 'hypnodrome_beta',
'clips': [
[36, 'MAX COOPER Order from Chaos', [], False] ,
[37, '8-bit Triangle Zoom', [], False] ,
[38, 'Unleash Your Fingers 1', [], False] ,
[39, 'LUSH PUPPIES', [], False] ,
[44, 'AZEL PHARA - GREEN', [], False] ,
[45, 'Cassettes', [], False] ,
[46, 'Kerli - Zero Gravity [mv]', [], False] ,
[47, "'Evening In Space' Directed by David LaChapelle", [], False] ,
[52, 'A E T H E R', [], False] ,
[53, 'Vicious Cycle', [], False] ,
[54, 'WILDLESS', [], False] ,
[55, "Ataxia 'Glitch'", [], False] ,
[60, 'ATARAXYA', [], False] ,
[61, 'MAX COOPER Remnants', [], False] ,
[62, 'SHY LUV - SHOCK HORROR', [], False] ,
[63, 'Bubbles', [], False] ,
[40, 'Octopus Project', [], False] ,
[41, '1 & 3 4', [], False] ,
[42, 'Monument', [], False] ,
[43, 'Tornado', [], False] ,
[48, 'Simulation', [], False] ,
[49, 'PHEROMONE', [], False] ,
[50, 'Sunset Powerlines Time Lapse', [], False] ,
[51, 'Glass of Water', [], False] ,
[56, 'CYCLE', [], False] ,
[57, 'Skateboard Chalk 2', [], False] ,
[58, 'Meteor Shower', [], False] ,
[59, 'Art of Walking', [], False] ,
[64, 'ISOLATED', [], False] ,
[65, 'Downliners', [], False] ,
[66, 'cnc', [], False] ,
[67, 'Integrated Webcam 1', [], False] ,
[69, 'Spleigher ', ['Fun', 'Slay', 'Contra', 'Distort', 'Brite', 'Brite'], False] ,
[70, 'Blow&Blur', ['BlowX', 'BlowY', 'Blur', 'Splits', 'Screens'], False] ,
[71, 'Flight', ['Tilt', 'Altitude', 'Height', 'Jags', 'Texture'], False] ,
[77, 'Cyberscope ', ['Angles', 'Rotate', 'Cyber', 'C-Pass', ''], False] ,
[78, 'Polyglitch', ['Color', 'Lines', 'Expand', 'Zoom', 'Fuzz'], False] ,
[85, 'Point Grid ', ['Points', 'Reso', 'Worms', 'Trails', 'Quads', '', '', ''], False] ,
[86, 'Pixelnoise', ['Noise', 'Reso', 'Satch', 'Fountain'], False] ,
[87, 'Tritunnel ', ['Tunnel', 'Speed', 'TurnX', 'TurnY', 'Fractality', '', '', ''], False] ,
[93, 'Salvia', ['Bonkers', 'Timelines', 'Copies', 'Losing Focus', '', ''], False] ,
[94, 'Fux Given', ['Rings', 'Parts', 'Fux', 'Lag', 'Twirl'], False] ,
[95, 'Lawl of Mirrors', ['Ocean', 'Flipper', 'Mirror', 'Mirror', 'Mirror', 'Mirror', '', ''], False] ,
[72, 'Posterize ', ['Posters', 'Satch'], True] ,
[73, 'Bzzzt ', ['RGB', 'Zoom', 'Light', 'Frames'], True] ,
[74, 'Stripwreck ', ['Yank', 'Tug', 'Strip', 'Wreck'], True] ,
[80, 'Horizontal ', ['Thick', 'Speed'], True] ,
[81, 'Recolour ', ['Wiggity', 'Floor It', 'Cellular', 'Deckade', '', '', '', ''], True] ,
[82, '', ['Color', 'Shape', 'Count', 'Edges', 'Rotate', 'Zoom', '', ''], True] ,
[88, 'Audiosucker ', ['Suck', 'Poster'], True] ,
[89, 'Oil Fire ', ['Distort', 'Spd', 'Deeds'], True] ,
[90, 'Chance of Hail ', ['Slow Pour', 'Size', 'Twist', 'Blue ^', 'Red v'], True] ,
[96, 'Dubs ', ['Dubs'], True] ,
[97, 'Triangulate ', ['Fractlity', 'Gentle'], True] ,
[98, 'Ballmer ', ['Shape', '3D Reso', '2D Reso', 'Darkweb'], True] ,
],
'quadrants': [{
  'mode': 'BASIC',
  'active': 6,
  'quadrant': 2,
  'palette': 1,
  'killer': constants.BUTTON_DELETE,
  'kill_other_layer_on_select': 1,
  'labels': ['STR', 'MAG', 'INT', 'DEX', 'CON', 'LCK'],
  'keys': [
    69, 70, 71,
    77, 78, 79,
    85, 86, 87,
    93, 94, 95
  ],
}, {
  'mode': 'BASIC',
  'active': 6,
  'quadrant': 3,
  'palette': 2,
  'killer': constants.BUTTON_UNDO,
  'kill_other_layer_on_select': 0,
  'keys': [
    72, 73, 74,
    80, 81, 82,
    88, 89, 90,
    96, 97, 98
  ],
}, {
  'mode': 'CLIPS',
  'active': 6,
  'quadrant': 0,
  'palette': 0,
  'killer': constants.BUTTON_QUANTIZE,
  'kill_other_layer_on_select': 3,
  'labels': ['intro', 'verse', 'chorus', 'bridge', 'break', 'outro'],
  'keys': [
    36, 37, 38, 39,
    44, 45, 46, 47,
    52, 53, 54, 55,
    60, 61, 62, 63
  ]
}, {
  'mode': 'CLIPS',
  'active': 6,
  'quadrant': 1,
  'palette': 0,
  'killer': constants.BUTTON_DOUBLE,
  'kill_other_layer_on_select': 2,
  'labels': ['intro', 'verse', 'chorus', 'bridge', 'break', 'outro'],
  'keys': [
    40, 41, 42, 43,
    48, 49, 50, 51,
    56, 57, 58, 59,
    64, 65, 66, 67
    ]
  }]
}
