# Polyglitch: Line Width on dashboard knobs didn't work - always bounces back to 63.
# had to change it to Num Lines.
from vjmagic import constants
config = {
'name': 'hypnodrome_gamma',
'clips': [
[36, 'MAX COOPER SEED', [], False] ,
[37, 'Jose Gonzalez Bouncy Balls', [], False] ,
[38, 'Fever the Ghost - Source [mv]', [], False] ,
[39, 'Contre Temps [as]', [], False] ,
[44, 'Our Fractal Brains', [], False] ,
[45, 'The Jump', [], False] ,
[46, 'Gravity [as]', [], False] ,
[47, 'Natalis [as]', [], False] ,
[52, 'Oh Land - White LIghts [mv]', [], False] ,
[53, 'IRL Fruit Ninja', [], False] ,
[54, 'brainslushy', [], False] ,
[55, 'Patterns', [], False] ,
[60, 'Max Cooper - Cyclic', [], False] ,
[61, 'Octopus Project', [], False] ,
[62, 'Max Cooper & Tom Hodge - Trust', [], False] ,
[63, 'LORN - ANVIL', [], False] ,
[40, 'Prophecy', [], False] ,
[41, 'City Without U', [], False] ,
[42, 'Kamau Jambo [dance]', [], False] ,
[43, 'Azaelia Banks - Chasing Time [mv]', [], False] ,
[48, 'Flyknit R&D', [], False] ,
[49, 'Longry', [], False] ,
[50, 'Oh Land - Sun of a Gun [mv]', [], False] ,
[51, 'Love & Theft ', [], False] ,
[56, 'SHHH! - Jack Sachs X Tate Britain', [], False] ,
[57, 'Simulation', [], False] ,
[58, 'PHEROMONE', [], False] ,
[59, 'LUSH PUPPIES', [], False] ,
[64, 'Unleash Your Fingers 1', [], False] ,
[65, 'Monument', [], False] ,
[66, 'Caravan Palace - Suzy [mv]', [], False] ,
[67, 'A BEAUTIFUL PERSON', [], False] ,
[69, 'Cyberscope ', ['Angles', 'Rotate', 'Cyber', 'C-Pass', '', 'Brite'], False] ,
[70, 'Fux Given', ['Rings', 'Parts', 'Fux', 'Lag', 'Twirl'], False] ,
[71, 'Lawl of Mirrors', ['Ocean', 'Flipper', 'Mirror', 'Mirror', 'Mirror', 'Mirror', ''], False] ,
[77, 'Blow&Blur', ['BlowX', 'BlowY', 'Blur', 'Splits', 'Screens'], False] ,
[78, 'Point Grid ', ['Points', 'Reso', 'Worms', 'Trails', 'Quads', '', ''], False] ,
[79, 'Polyglitch', ['Color', 'Lines', 'Expand', 'Zoom', 'Fuzz'], False] ,
[85, 'Pixelnoise', ['Noise', 'Reso', 'Satch', 'Fountain', 'Quads', '', ''], False] ,
[86, 'Spleigher ', ['Fun', 'Slay', 'Contra', 'Distort', 'Brite', ''], False] ,
[87, 'Salvia', ['Bonkers', 'Tmelines', 'Copies', 'Folds', '', '', ''], False] ,
[93, 'Rotating Panels', ['Craze', 'Edge', 'Confuse', 'Losing Focus', ''], False] ,
[94, 'Happy Trails', ['Trails', 'Perma', 'Fux', 'Lag', 'Twirl'], False] ,
[95, 'Tritunnel ', ['Tunnel', 'Speed', 'TurnX', 'TurnY', 'Fractality', '', ''], False] ,
[72, 'Audiosucker ', ['Suck', 'Poster'], True] ,
[73, 'Busta Rhymes ', ['Invert', 'Focus', '', 'Frames'], True] ,
[74, 'Stripwreck ', ['Yank', 'Tug', 'Strip', 'Wreck'], True] ,
[80, 'Bzzzt ', ['RGB', 'Zoom', 'Light', 'Frames'], True] ,
[81, 'Intersectional ', ['Thin', 'Rate', 'Cellular', 'Deckade', '', '', ''], True] ,
[82, 'Wiggity Wack ', ['Wiggity', 'Floor It', 'Cellular', 'Deckade', 'Rotate', 'Zoom', ''], True] ,
[88, 'Posterize ', ['Posters', 'Satch'], True] ,
[89, 'Oil Fire ', ['Distort', 'Spd', 'Deeds'], True] ,
[90, 'Chance of Hail ', ['SlowPour', 'Size', 'Twist', 'Blue ^', 'Red v'], True] ,
[96, 'Dubs ', ['Dubs', 'Drops'], True] ,
[97, 'Triangulate ', ['Fractlty', 'Gentle'], True] ,
[98, 'Ballmer ', ['Shape', '3D Reso', '2D Reso', 'Darkweb'], True] ,
],
'quadrants': [{
  'mode': 'BASIC',
  'active': 6,
  'quadrant': 2,
  'palette': 1,
  'killer': constants.BUTTON_DELETE,
  'kill_other_layer_on_select': 1,
  'labels': ['STR', 'MAG', 'INT', 'DEX', 'CON', 'LCK'],
  'keys': [
    69, 70, 71,
    77, 78, 79,
    85, 86, 87,
    93, 94, 95
  ],
}, {
  'mode': 'BASIC',
  'active': 6,
  'quadrant': 3,
  'palette': 2,
  'killer': constants.BUTTON_UNDO,
  'kill_other_layer_on_select': 0,
  'keys': [
    72, 73, 74,
    80, 81, 82,
    88, 89, 90,
    96, 97, 98
  ],
}, {
  'mode': 'CLIPS',
  'active': 6,
  'quadrant': 0,
  'palette': 0,
  'killer': constants.BUTTON_QUANTIZE,
  'kill_other_layer_on_select': 3,
  'labels': ['intro', 'verse', 'chorus', 'bridge', 'break', 'outro'],
  'keys': [
    36, 37, 38, 39,
    44, 45, 46, 47,
    52, 53, 54, 55,
    60, 61, 62, 63
  ]
}, {
  'mode': 'CLIPS',
  'active': 6,
  'quadrant': 1,
  'palette': 0,
  'killer': constants.BUTTON_DOUBLE,
  'kill_other_layer_on_select': 2,
  'labels': ['intro', 'verse', 'chorus', 'bridge', 'break', 'outro'],
  'keys': [
    40, 41, 42, 43,
    48, 49, 50, 51,
    56, 57, 58, 59,
    64, 65, 66, 67
    ]
  }]
}
